### ISSUE TITLE
Prevent institution e-mail from being same as user login

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/enrolment#107]
**Requirements:**

* Prevent Users from entering an Institution e-mail that is the same as their registered account e-mail.
* This occurs in two flows:
(1) When a User (e.g. PI) is adding a new Project and must supply their profile info.
(2) When a new User is added to a Project and must supply their profile info.

**Background:**

The User's academic, business, scientific, or research institution should not be their Gmail.

In the past when enrolment was done via PDF forms, the forms prevented re-use of Gmail as institution e-mail.  We'd like to extend this validation to the Enrolment UI.

**Screenshots:**

![Disallow Gmail as Institution Email.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bd8b1f2211ba000118269d6/125516c66e82c728ace21e0d46cc9d89228e8fa698a9984ea554fcd42855675a2717b7226490f721b04c3b24020e17f053444d04bea6d37ef5f22e7a98595aec853e5c7c956f18fdbd8217bf00b2258246d7e3e98f5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cf442e84e5ca7133267ee647b.png)

**Comment by jmimico** [comment]
Any update on this issue? We are having more and more people sign up incorrectly with duplicate emails. It's becoming a bit of a mess.

**Comment by b-f-chan** [comment]
No update, this hasn't made it into any sprint anywhere.  Let's talk with @Fgerthoffert tomorrow, maybe we can start giving some minor Enrolment tickets to new developers who join.

New Devs will probably need to ramp-up and work on more priority projects, but if we can have them even fix 1 or 2 Enrolment tickets here and there, we can whittle away at these tickets and squeeze a few improvements in.

**Comment by b-f-chan** [comment]
Blocked by: https://github.com/overture-stack/charts/issues/2

**Comment by b-f-chan** [comment]
PR #118
