### ISSUE TITLE
User directed to Projects & Users dashboard before & after approval

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/enrolment#110]
**User Feedback from @jmimico :**

* Once a User is invited to a project, logs in, and fills in their info, they directed to the Projects & Users dashboard were they can register a project.
* The User is **always** directed to the dashboard before **AND** after they are approved by OICR admin.
* This can be a confusing experience, since before approval they should not be able to see or access this dashboard.  Granted, the dashboard is blank before approval, but it may seem odd or leave them feeling stranded in the UI.

**Request:**

* Overall, the user experience and flows of Enrolment warrant a re-analysis and re-design if time permits.
* This flow is one area to consider improving.

**Comment by caravinci** [comment]
As of #115, when an invited user logs in, they are received with this:
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/b683b32b-aaee-4cfc-9960-9b5210ad2b2d)
where they are able to accept the invitation, fill the form with their data and submit it.

Once their submission is approved by the staff, then users are met with this:
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/6040d25e-e72b-4de7-9b9e-a0e6c5aa4757)

Would this be considered a sufficient enhancement at this point? @b-f-chan @jmimico
