### ISSUE TITLE
More detail should be displayed in the Application requests table for the admin user

### ISSUE THREAD

**Issue by jmimico** [overture-stack/enrolment#113]
Currently as an admin of the enrolment system I see the following information in our lists of projects:

Request ID | Project Title | Created Date | Updated Date | Status | Action

I would request that the 'Institution Name' and 'first name last name' and 'institution' email be one of the fields displayed/added in this table. Request ID and project title are not important for us to manage projects and could be not displayed in this particular table.

Without this information in this main table the application is very unusable from an administration standpoint.

**Comment by b-f-chan** [comment]
Blocked by: https://github.com/overture-stack/charts/issues/2

**Comment by b-f-chan** [comment]
PR #117
