### ISSUE TITLE
PI e-mail invitations to users of a project should be re-sendable

### ISSUE THREAD

**Issue by jmimico** [overture-stack/enrolment#115]
When a PI has a registered project and invites a user to be a part of that project sometimes the email sent to the user goes to spam, or gets deleted and without that link the user cannot enrol themselves in to the system. The PI and/or the oicr admins should be able to re-send this email.

**Comment by caravinci** [comment]
Aside from being able to resend an email, the invited users should see their invitations in their dashboard, without the need to create a project of their own. Thus, users don't rely on the invitation email at all.

**Comment by jmimico** [comment]
> Aside from being able to resend an email, the invited users should see their invitations in their dashboard, without the need to create a project of their own. Thus, users don't rely on the invitation email at all.

I agree, this would be a useful improvement

**Comment by b-f-chan** [comment]
E-mail fix as described by @jmimico: 

> Problem: postfix needs to allow-list a subnet of sending IP addresses which in our case is the IP’s of the enrolment applications docker network (192.168.32.0/20). The reason it didnt work is because in production the docker network is using a different subnet.

After e-mail fix, we tested re-sending all previously blocked/unreceived e-mails, and they were successfully received (although often getting caught by gmail's spam folder).  Enrolment flow could be completed from the e-mails.

Ready for PR review.

**Comment by caravinci** [comment]
The issue sending emails from the Lab environment was caused mainly by the varying subnet arrangement created every time docker composed its network. We've amended the PR with some changes to correct that, and thus ensure closer parity between prod and lab.
