### ISSUE TITLE
Admin dashboard - poor formatting / unable to deny projects

### ISSUE THREAD

**Issue by jmimico** [overture-stack/enrolment#120]
Since adding additional columns to the main dashboard for admins, this has resulted in some formatting problems and an inability to deny projects due to overlapping elements.

Please see screenshot

![Screen Shot 2019-03-21 at 11 30 52 AM](https://user-images.githubusercontent.com/19290745/54763826-0c678300-4bcd-11e9-90c6-b8dc67f5b445.png)

**Comment by b-f-chan** [comment]
Tested at https://lab-enrolment.cancercollaboratory.org/

Table is fixed, right side of table no longer bleeds into the right column if it is too wide.  Instead, horizontal scrollbar is provided and user can freely scroll without any overlap into the margin.

Ready for PR review.
