### ISSUE TITLE
Fix security warnings in Enrollment repo

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/enrolment#122]
There are many issues:
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/bb9f895e-863c-4277-bddf-e4759d6416ac)

**Comment by rosibaj** [comment]
Complete after @joneubank has done the persona repo as some of these will be resolved!

**Comment by d8660091** [comment]
@rosibaj Is the page located at https://github.com/overture-stack/enrolment/security/advisories, I am not able to see the alerts.

**Comment by rosibaj** [comment]
@d8660091 Its located here: https://github.com/overture-stack/enrolment/network/alerts

**Comment by rosibaj** [comment]
I see no more errors in the repository - thanks @d8660091 !!!!

**Comment by rosibaj** [comment]
@joneubank @d8660091 Can we document either why all these were dismissed or a change to the package.json so that the decision is recorded please?

**Comment by d8660091** [comment]
These alerts are dismissed because they are either dependencies of `react-scripts`, which couldn't be upgraded, or dependencies that does not effect the transpiled js code

**Comment by rosibaj** [comment]
@d8660091 Would it be possible to revisit this and either
1)  actually update the dependencies -or-
2) move to dev dependencies?

I've discussed with @joneubank and @andricDu and 2) should be sufficient for this repository.

**Comment by alekspejovic** [comment]
- Correct thing to do is move these into dev dependencies
