### ISSUE TITLE
Rename 'Position' to 'Job Title' to avoid being lost in translation

### ISSUE THREAD

**Issue by jmimico** [overture-stack/enrolment#144]
In the user signup form we ask for the users 'Position' which is intended to be their job title. What we have observed is that many of our applicants are putting in their geo-location (ie; China) instead. I think clearer language should be used to avoid being lost in translation. 

Knowing the job title is useful when trying to determine if the persons role is in a leadership position with budget to pay for computing costs.

**Comment by b-f-chan** [comment]
Tested at https://lab-enrolment.cancercollaboratory.org/

Label has been changed in all places it appears, ready for PR review
