### ISSUE TITLE
Fix Dismissed Security Vulnerabilities

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/enrolment#149]
Fix 12 incorrectly dismissed security vulnerabilities.

Unfortunately you cannot "undismiss" dismissed vulnerabilities in GitHub, so we need to look at the history of "Closed" alerts and click each one for details.

These 12 are the ones wrongly dismissed (_NEVER FIXED_) by Xu in July, 2019:

https://github.com/overture-stack/enrolment/network/alerts?q=is%3Aclosed

![Screen Shot 2019-11-21 at 10 06 16 AM](https://user-images.githubusercontent.com/40768946/69349899-97aa8400-0c46-11ea-8060-d9fd53347896.png)

**Comment by caravinci** [comment]
Oh boy...

**Comment by caravinci** [comment]
Superseded by #157
