### ISSUE TITLE
[Security Vulnerability] Upgrade Handlebars Version

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/enrolment#151]
Upgrade handlebars version to fix latest GitHub security vulnerability in enrolment-ui repo:
https://github.com/overture-stack/enrolment/network/alert/enrolment-ui/yarn.lock/handlebars/open

<img width="1053" alt="Screen Shot 2020-01-02 at 10 48 12 PM" src="https://user-images.githubusercontent.com/40768946/71676134-fcaed900-2db1-11ea-87c1-aa339b6fbe7b.png">

**Comment by caravinci** [comment]
Closing in favour of #157
