### ISSUE TITLE
[Security Vulnerability] Upgrade Django Version

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/enrolment#152]
Upgrade handlebars version to fix latest GitHub security vulnerability in enrolment repo:
https://github.com/overture-stack/enrolment/network/alert/enrolment-service/requirements.txt/Django/open

![Screen Shot 2020-01-20 at 9.45.57 AM.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/e994346c-eaf4-4941-a594-1c666bdda170)

**Comment by b-f-chan** [comment]
Sanity tested on lab-enrolment.cancercollaboratory.org

Unfortunately one validation is no longer working, specifically the Institution E-mail must be different from the Billing Contact e-mail

In prod, it correctly shows the validation message and prevents the user from proceeding:

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/80848b27-db44-4d25-90b8-f9f62aa438bf)

However, in lab, the message is NOT shown and the user can proceed to the end of the wizard - However, once they try to submit the final request, the confirmation e-mail is not sent and no request is created, it just remains on the final screen, but without any error message

It seems the validation is still there but failing at the end silently and not giving any notice to the user

The code was not changed, so it could be some broken dependency or environmental issue after fixing the recent security vulnerabilities

**Comment by caravinci** [comment]
Restarted this branch, this time updating Django to v1.11.29.
This major version has not been supported since April 2020, and we should move to at least v3.2, whose EOL is some time in 2024.
Latest major is v5.

The issues experienced in the previous tests were likely due to environment setup, as the lab doesn't run an independent instance of DACO. Further testing could be completed once deployed to prod, with a fast rollback should the issues persist.

**Comment by b-f-chan** [comment]
Tested at: https://lab-enrolment.cancercollaboratory.org/

**The following tests work correctly/successfully same as prod:**

- PI login, logout
- Admin login, logout
- Register new project
- View existing project details
- Terminate project
- Add new user
- View existing users
- Admin approve project request
- Admin deny project request

**Pending tests:**

- Currently cannot test new user e-mail invite flow, e-mail does not seem to be setup in lab, @caravinci is investigating

**Comment by b-f-chan** [comment]
After discussions with @caravinci @jmimico, we need to further investigate why e-mail sending is being blocked (perhaps IT is blocking this node).  We will investigate separately in #168.

Since we did not touch the e-mail invitation code, this security update should be low risk in impacting that functionality.  We can PR review and release to prod; I will test the invitation flow immediately and if something is amiss we can rollback.
