### ISSUE TITLE
Capture billing contact email address

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/enrolment#165]
@akachru-github commented on [Tue Sep 22 2020](https://github.com/overture-stack/billing/issues/101)

When someone registers for a project they use the enrolment application which asks for all sorts of contact details, including an alternate billing contact however it does not ask for a billing contact email address.

And since we send out invoices by email, we would need an email address associated with the billing contact.

**Comment by caravinci** [comment]
Adding billing contact info, wouldn't it make sense to also allow for them to submit a phone number? @akachru-github @jmimico

**Comment by b-f-chan** [comment]
Tested in lab:

- Success: New billing contact e-mail field appears if different billing contact selected
- Success: Field validates correctly (must be properly formatted e-mail, cannot be empty / is mandatory)
- Success: Billing e-mail persists after project submission / creation
- **Missing:** The billing contact Full Name is optional, but it should be mandatory (can we fix as part of this ticket?  seems straightforward)

**Comment by caravinci** [comment]
Those are easy enough to do in this same ticket.
Changes made to the "Full Name" field:
- relabelled as "Contact Name"
- made mandatory

Testable at Lab

**Comment by jmimico** [comment]
<img width="646" alt="Screen Shot 2021-02-02 at 12 23 41 PM" src="https://user-images.githubusercontent.com/19290745/106638341-c5c96a80-6551-11eb-8fc3-4987a2709516.png">

Billing Contact Name is unlike other 'required' fields and doesn't say required on empty field. Should probably make this consistent

**Comment by caravinci** [comment]
You're right. I've missed that spot. Amending the PR
