### ISSUE TITLE
Improve layout responsiveness

### ISSUE THREAD

**Issue by caravinci** [overture-stack/enrolment#181]
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/0f73f231-84c6-4219-b788-eb99f4837854)

**Comment by caravinci** [comment]
To avoid making the layout unbound, I've extended it to a maximum of 1920px.
Deployed to lab and ready to be tested.

**Comment by b-f-chan** [comment]
Tested in lab:

- Layout width increased, wider than in prod and takes up the wasted whitespace
- No bleeding into columns or panels noticed

Ready for PR review
