### ISSUE TITLE
Enable admins to manage project status "cul-de-sacs"

### ISSUE THREAD

**Issue by caravinci** [overture-stack/enrolment#182]
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/a9a77ee2-83a9-4442-8dd6-993dd86ec3c7)

Ticket intended to "undeny", "unapprove", and "unterminate" projects and users.

**Caveat: Purged data cannot be restored.**

**Comment by caravinci** [comment]
Setting up the following admin-only actions, based on Project status (I've already added the ones in **bold**):
- Pending:
    - Approve
    - Deny
    - _Should we add something to terminate without sending an email?_
- Approved:
    - "No action needed"
    - _Should we add something to terminate without sending an email?_
- Termination Request:
    - Confirm
    - **Reject** (goes back to Approved)
- Terminated/Denied:
    - Purge
    - **Reassess** if Denied (goes back to Pending, for further review)
    - **Reopen** if Terminated (goes back to Approved)

@jmimico thoughts about those two possible additions (at Pending and Approved)?

**Comment by caravinci** [comment]
Changed scope of tickets to Projects only. User management to be delegate to existing, older ticket #7

**Comment by b-f-chan** [comment]
@caravinci - I agree, I think the 3 actions you implemented should send e-mails to inform the user, both because it is the right thing to do and for consistency with our other actions.  However, want to hear what @jmimico thinks.

Additionally, I don't think I can test these since I am not an Admin on lab-enrolment.  I can't see the new action buttons for projects in each of those states :(.  Either I will need to be made Admin or @jmimico will need to test this.

**Comment by b-f-chan** [comment]
Got admin access and tested in lab:

- If user requested project termination, admin sees status correctly as "Termination Requested", with Approve and Deny buttons visible
- If admin approves termination or terminates themselves, status correctly goes to "Terminated"
- If admin rejects termination request, status correctly goes back to "Approved"
- In "Terminated" state, Purge and Re-Open actions correctly display
- If admin re-opens project, status correctly goes back to "Approved"
- If admin purges project, entry correctly removed from table after confirmation

@jmimico @caravinci - Tested the scope of this ticket (just the bold actions) and it works fine for me.  Will let @jmimico test and confirm himself too, but I think it's ready for PR review.

I think we should add the e-mail notifications also, but we can address as separate ticket that @caravinci can pickup later if he needs to move onto other projects after this week.

**Comment by jmimico** [comment]
Tested and appears to work as designed

**Comment by caravinci** [comment]
Splendid. Will open a PR and put it up for review. Thank you both! @b-f-chan @jmimico
