### ISSUE TITLE
Create a PDF of Collaboratory terms and conditions and add it to the production env instead of ICGC's

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/enrolment#50]
![screen shot 2017-11-30 at 4 50 36 pm](https://user-images.githubusercontent.com/5667028/33456840-9bd9bd10-d5ee-11e7-9b9f-58611e0e76e9.png)

**Comment by lepsalex** [comment]
This link is configurable, we can include it in assets and link to it or we can link to a webpage containing the terms if it exists.

**Comment by lepsalex** [comment]
App now uses latest link sent via email
