### ISSUE TITLE
Project registration email changes

### ISSUE THREAD

**Issue by jmimico** [overture-stack/enrolment#69]
I think we should change the way emails are sent to users when a project is created to be sent to everyone as bcc: and we should be sending these emails to ~~help@cancercollaboratory.org~~ register@cancercollaboratory.org instead of george.mihaiescu@oicr.on.ca

Example:
---------- Forwarded message ----------
From: <no-reply@cancercollaboratory.org>
Date: Thu, Jan 4, 2018 at 11:43 AM
Subject: Collaboratory - New Project from Jared Baker: Project test emails
To: george.mihaiescu@oicr.on.ca
Cc: jaredbaker@gmail.com
Hello, 
A new Project Application has been submitted. Details below: 
<-snip->

**Comment by jmimico** [comment]
Updated email address in main bug report

**Comment by lepsalex** [comment]
Complete, new register@cancercollaboratory.org email address being used.

**Comment by jmimico** [comment]
Hey Alex,

I referred to the original workflow spec

https://wiki.oicr.on.ca/display/DCCSOFT/Collaboratory+-+Manage+Projects+and+Users?preview=%2F73203730%2F79072418%2Fmockup_project_enrollment_WF.png

Looks like we need the registration emails need to be sent TO: help@cancercollaboratory.org and CC: the PI registering the project.

Sorry for the confusion on this.
