### ISSUE TITLE
User enrolment link broken in email. 

### ISSUE THREAD

**Issue by andricDu** [overture-stack/enrolment#70]
This link is broken:
<img width="578" alt="screen shot 2018-01-09 at 3 44 52 pm" src="https://user-images.githubusercontent.com/6350043/34742388-0b91f472-f554-11e7-9d8a-b17ae8b33ff8.png">

It points to the `local.enrol....` URL.

**Comment by andricDu** [comment]
making this high priority as users are actively trying to use the link.

**Comment by lepsalex** [comment]
Fix is applied and committed, need to rebuild the docker container in production, will do that first thing tomorrow.

**Comment by lepsalex** [comment]
Complete and in production.
