### ISSUE TITLE
Approved projects have mysterious 'Enrol Users' link that seems to do nothing

### ISSUE THREAD

**Issue by jmimico** [overture-stack/enrolment#77]
See screenshot @ https://imgur.com/a/9MQUE

The 'Enrol users' link doesnt seem to do anything (i tried firefox and chrome) however the 'Add users' on the right hand side seems to work.

This should probably be cleaned up to avoid confusion with the user.

**Comment by rosibaj** [comment]
We will remove the Enrol Users button: 

Spec here:  https://wiki.oicr.on.ca/display/DCCSOFT/Updates+to+Enrollment .
