### ISSUE TITLE
[user impacting] Adding users to a project appears to be broken

### ISSUE THREAD

**Issue by jmimico** [overture-stack/enrolment#78]
Both a user and myself see this issue. Please see the attached screenshot. Adding a user to an approved project does not appear to work. The form is broken and unresponsive. Tried chrome/firefox so far

https://imgur.com/a/9zMO7

**Comment by andricDu** [comment]
![image](https://user-images.githubusercontent.com/6350043/37427435-db177c6c-279f-11e8-8c92-0cd079b5519e.png)

**Comment by lepsalex** [comment]
Bootstrap "latest" switched to 4.x build that broke many things, have locked to 3.x and all is as it was.
