### ISSUE TITLE
[feature enhancement] Identifying project for new users of an existing project

### ISSUE THREAD

**Issue by jmimico** [overture-stack/enrolment#79]
When managing user requests on existing projects we should display in the UI table, a column that has the project title.

We should also include new user **email** notifications to include the project title somewhere in the subject or body of the email.

![image](https://user-images.githubusercontent.com/19290745/37485956-69fc7f36-2863-11e8-9155-045952d41b9b.png)

**Comment by caravinci** [comment]
Seems the user invitation already includes the Project's name, both in the subject and the body.
Deploying changes to add the requested column to the users Table into Lab environment.
Ready for tests.

**Comment by b-f-chan** [comment]
Tested in lab:

- Verified user invite already includes Project name in e-mail subject & body
- Extra Project Name column now correctly displays in Admin UI Dashboard

Ready for PR review

**Comment by jmimico** [comment]
Project column looks good in lab deployment
