### ISSUE TITLE
Enrolment app - DACO message bug?

### ISSUE THREAD

**Issue by mbrazas** [overture-stack/enrolment#90]
Within the enrolment app webpage, I tried to login as an External user using my Google credentials.
I do not believe that I am on the DACO approved users list, so this would be a good test for external users who are not yet approved.

I can enter my Google credentials, but then I get bumped out of logging in and returned to the enrolment app homepage without a message redirecting me to register at DACO (screenshot below)

![screen shot 2018-06-21 at 12 33 52 pm](https://user-images.githubusercontent.com/7570352/41732678-a566f162-754f-11e8-95a3-7c00553dd032.png)

**Comment by b-f-chan** [comment]
Hi @mbrazas, I believe this issue is no longer valid, since we've removed the DACO check.

Can you please confirm and I'll close this?  Thanks!

**Comment by mbrazas** [comment]
This probably works now, but I cannot test it as I do not have an account on Collab.
Michelle

**Comment by rosibaj** [comment]
@b-f-chan Any way we can test and confirm that this ticket is no longer needed?

**Comment by b-f-chan** [comment]
Thanks @rosibaj , just tested this and had a new user non-registered user (Touhidul) try it as well.  The error no longer appears and user can login with their Google account and request project registration.  Closing.
