### ISSUE TITLE
Major redesign of the enrolment app

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/enrolment#92]
The aim of this ticket is to contain a list of items to take in consideration while preparing specs for the new major version of the enrolment/billing app.

**Registration process**
 - Find a way to reliably physically identify users; this could be done through credit card verification (see stripe), or other means (sending copy of an ID ?)
 - Collect credit card payment upfront to allow for automated invoicing/billing at the end of a cycle
 - Allow creation of tenants (projects)
 - Allow adding/removal of users from projects

**Metrics collection**
 - Track the multiple metrics: VM usage, Storage usage, external download usage, workflow execution usage, ...
 - Provide reporting / usage trends on those metrics

**Billing**
 - Automatically charge users for their usage.
 - Support discount (global, per project)

**Misc**
 - Support single sign on with openstack console, ICGC portal, ...

**Comment by mbrazas** [comment]
DACO authentication (Misc) for download only users
